fix: file storage widget fails to load due to Python error trying to call `tr()` statically on `QObject`
Just make a tmp `QObject`, used in several other places too.

Error:
```
TypeError: tr(self, sourceText: str, disambiguation: str = None, n: int = -1): first argument of unbound method must have type 'QObject'
```