Fix missing HTTP code from the reply for unknown reason
Otherwise we get:
```
TypeError: '>=' not supported between instances of 'NoneType' and 'int'
Traceback (most recent call last):
  File "/home/suricactus/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qfieldsync/core/cloud_api.py", line 392, in
    lambda: self._on_cloud_get_download_finished(
  File "/home/suricactus/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qfieldsync/core/cloud_api.py", line 423, in _on_cloud_get_download_finished
    if http_code >= 301 and http_code TypeError: '>=' not supported between instances of 'NoneType' and 'int'
```